#!/usr/bin/env python3
"""
Single-command end-to-end runner for one match video.

Replaces the multi-script workflow:
    python scripts/run_pipeline.py ...
    python -m track_annotation.cli inspect ...
    streamlit run src/track_annotation/reviewer/app.py ...

with a single invocation that handles all common cases.

Modes
-----
1) Auto: looks for a sidecar meta.yaml; if present uses it, otherwise prompts
   for --kit-context and uses no team filter.

2) --auto-calibrate: runs auto_calibrate_kit.py to cluster torsos, prints
   instructions for picking a cluster, then exits. Re-run with --cluster-id N
   to finalize meta and continue.

3) --no-filter: bypass team color filter entirely. Useful for first run on a
   new kit when you don't know HSV ranges yet — generates more tracks
   (including opponents) but at least you can see what the pipeline produces.

Examples
--------
    # Sidecar meta exists → just run end-to-end
    python scripts/run_match.py --video data/videos/match.mp4

    # No filter (quick smoke test, all persons tracked)
    python scripts/run_match.py --video data/videos/match.mp4 --no-filter

    # Auto-calibrate workflow (2 steps)
    python scripts/run_match.py --video data/videos/match.mp4 --auto-calibrate
    # → prints "inspect /tmp/calib/cluster_*.jpg, pick one, re-run with --cluster-id N"
    python scripts/run_match.py --video data/videos/match.mp4 --auto-calibrate --cluster-id 1

    # After successful run, also launch reviewer
    python scripts/run_match.py --video data/videos/match.mp4 --launch-reviewer
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))


def _section(title):
    bar = "=" * 60
    print(f"\n{bar}\n  {title}\n{bar}")


def _ok(msg):
    print(f"  \033[92m✓\033[0m {msg}")


def _warn(msg):
    print(f"  \033[93m!\033[0m {msg}")


def _err(msg):
    print(f"  \033[91m✗\033[0m {msg}")


def _step_validate_setup():
    _section("1/5  Validate setup")
    weights = ROOT / "weights" / "yolo11l.pt"
    brands = ROOT / "data" / "logo_templates" / "brands.yaml"
    cfg = ROOT / "configs" / "person_tracking.yaml"

    failures = 0
    if not weights.exists():
        _err(f"weights missing: {weights}")
        _warn("  download: wget -O weights/yolo11l.pt "
              "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11l.pt")
        failures += 1
    else:
        _ok(f"weights        {weights.relative_to(ROOT)}  ({weights.stat().st_size / 1e6:.0f} MB)")

    if not brands.exists():
        _err(f"brand registry missing: {brands}")
        failures += 1
    else:
        _ok(f"brand registry {brands.relative_to(ROOT)}")

    if not cfg.exists():
        _err(f"config missing: {cfg}")
        failures += 1
    else:
        _ok(f"config         {cfg.relative_to(ROOT)}")

    try:
        import torch
        if torch.cuda.is_available():
            _ok(f"GPU            {torch.cuda.get_device_name(0)}")
        else:
            _warn("no CUDA GPU detected — pipeline will be SLOW on CPU")
    except ImportError:
        _err("torch not installed")
        failures += 1

    if failures:
        _err(f"\n{failures} setup check(s) failed. Aborting.")
        sys.exit(2)


def _step_resolve_meta(args) -> Path:
    _section("2/5  Resolve match metadata")
    video = args.video
    sidecar = video.with_suffix("").with_suffix(".meta.yaml")  # video.mp4 → video.meta.yaml
    if not sidecar.name.endswith(".meta.yaml"):
        sidecar = Path(str(video.with_suffix("")) + ".meta.yaml")

    if args.no_filter:
        _warn("--no-filter mode: bypass team color filter")
        return _write_no_filter_meta(sidecar, args.kit_context, args.opponent)

    if args.auto_calibrate:
        if args.cluster_id is None:
            _calibrate_and_exit(args, sidecar)
        else:
            _calibrate_and_write(args, sidecar)
            _ok(f"meta written : {sidecar}")
            return sidecar

    if sidecar.exists():
        _ok(f"using sidecar: {sidecar}")
        return sidecar

    _err(f"no meta.yaml found: {sidecar}")
    print("\n  Pick one of the following:")
    print(f"    A) Create {sidecar.name} manually (see data/videos/match.meta.example.yaml)")
    print(f"    B) Re-run with --auto-calibrate to generate one")
    print(f"    C) Re-run with --no-filter --kit-context home (skip team filter)")
    sys.exit(2)


def _write_no_filter_meta(path: Path, kit_context: str, opponent: str | None) -> Path:
    lines = [
        "# Auto-generated by run_match.py --no-filter",
        "# Team color filter disabled — all persons tracked, including opponents.",
        f"kit_context: {kit_context}",
    ]
    if opponent:
        lines.append(f'opponent: "{opponent}"')
    lines += [
        "",
        "target_team:",
        "  primary_colors: []      # empty list disables the filter",
        "",
        "ignore_regions:",
        "  - [0.00, 0.85, 0.50, 1.00]    # scoreboard placeholder — update for your broadcast",
        "  - [0.85, 0.00, 1.00, 0.15]    # channel logo placeholder",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
    _ok(f"wrote no-filter meta: {path}")
    return path


def _calibrate_and_exit(args, sidecar: Path):
    _section("Calibration: clustering torsos")
    out = ROOT / ".cache" / "calib" / args.video.stem
    cmd = [
        sys.executable, str(ROOT / "scripts" / "auto_calibrate_kit.py"),
        "--video", str(args.video),
        "--output", str(out),
        "--n-frames", str(args.n_calib_frames),
        "--k", str(args.k_clusters),
    ]
    print("  $", " ".join(cmd))
    subprocess.run(cmd, check=True)
    print()
    print(f"  Inspect:   {out}/cluster_*.jpg")
    print(f"  Then run:  python scripts/run_match.py --video {args.video} \\")
    print(f"                 --auto-calibrate --cluster-id N")
    sys.exit(0)


def _calibrate_and_write(args, sidecar: Path):
    _section("Calibration: writing meta from picked cluster")
    out = ROOT / ".cache" / "calib" / args.video.stem
    cmd = [
        sys.executable, str(ROOT / "scripts" / "auto_calibrate_kit.py"),
        "--video", str(args.video),
        "--output", str(out),
        "--n-frames", str(args.n_calib_frames),
        "--k", str(args.k_clusters),
        "--cluster-id", str(args.cluster_id),
        "--kit-context", args.kit_context,
        "--write-meta", str(sidecar),
        "--min-team-score", str(args.min_team_score),
    ]
    if args.opponent:
        cmd += ["--opponent", args.opponent]
    print("  $", " ".join(cmd))
    subprocess.run(cmd, check=True)


def _step_run_pipeline(args, meta_path: Path) -> Path:
    _section("3/5  Run detect+track+package")
    output_dir = ROOT / "data" / "annotation_packages" / args.video.stem
    cmd = [
        sys.executable, str(ROOT / "scripts" / "run_pipeline.py"),
        "--video", str(args.video),
        "--config", str(ROOT / "configs" / "person_tracking.yaml"),
        "--output", str(output_dir),
        "--match-meta", str(meta_path),
    ]
    if args.max_duration:
        cmd += ["--max-duration", str(args.max_duration)]
    print("  $", " ".join(cmd))
    print()
    proc = subprocess.run(cmd)
    if proc.returncode != 0:
        _err(f"\nPipeline failed with exit code {proc.returncode}. See log above.")
        sys.exit(proc.returncode)
    return output_dir


def _step_inspect(output_dir: Path):
    _section("4/5  Inspect package")
    cmd = [sys.executable, "-m", "track_annotation.cli", "inspect", "--package", str(output_dir)]
    env = os.environ.copy()
    env["PYTHONPATH"] = str(ROOT / "src") + os.pathsep + env.get("PYTHONPATH", "")
    subprocess.run(cmd, env=env)


def _step_launch_reviewer(output_dir: Path, port: int):
    _section("5/5  Launch reviewer")
    cmd = [
        "streamlit", "run",
        str(ROOT / "src" / "track_annotation" / "reviewer" / "app.py"),
        "--server.port", str(port),
        "--server.headless", "true",
        "--", "--package", str(output_dir),
    ]
    env = os.environ.copy()
    env["PYTHONPATH"] = str(ROOT / "src") + os.pathsep + env.get("PYTHONPATH", "")
    print("  $", " ".join(cmd))
    print(f"\n  Opening http://localhost:{port}  (Ctrl+C to stop)\n")
    try:
        subprocess.run(cmd, env=env)
    except KeyboardInterrupt:
        print("\n  Reviewer stopped.")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--video", type=Path, required=True)
    p.add_argument("--max-duration", type=float, default=None,
                   help="Limit pipeline to N seconds (testing). Default: full video.")

    g = p.add_argument_group("meta resolution")
    g.add_argument("--kit-context", default="home", choices=["home", "away", "special", "any"])
    g.add_argument("--opponent", default=None)
    g.add_argument("--no-filter", action="store_true",
                   help="Skip team color filter — keep every person track.")
    g.add_argument("--auto-calibrate", action="store_true",
                   help="Run auto-calibration to suggest HSV ranges.")
    g.add_argument("--cluster-id", type=int, default=None,
                   help="With --auto-calibrate: which cluster to use as target.")
    g.add_argument("--n-calib-frames", type=int, default=40)
    g.add_argument("--k-clusters", type=int, default=3)
    g.add_argument("--min-team-score", type=float, default=0.10)

    g2 = p.add_argument_group("post-pipeline")
    g2.add_argument("--launch-reviewer", action="store_true",
                    help="After successful run, launch Streamlit reviewer.")
    g2.add_argument("--reviewer-port", type=int, default=8501)

    args = p.parse_args()

    if not args.video.exists():
        sys.exit(f"Video not found: {args.video}")

    _step_validate_setup()
    meta_path = _step_resolve_meta(args)
    output_dir = _step_run_pipeline(args, meta_path)
    _step_inspect(output_dir)

    if args.launch_reviewer:
        _step_launch_reviewer(output_dir, args.reviewer_port)
    else:
        _section("Done")
        _ok(f"Package: {output_dir}")
        print(f"\n  Launch reviewer:")
        print(f"    bash scripts/run_reviewer.sh {output_dir.relative_to(ROOT)}")
        print(f"  or pass --launch-reviewer next time.")


if __name__ == "__main__":
    main()
